'use client'
import { useState } from 'react'
import Link from 'next/link'
import { CheckCircle2, Circle,Clock } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { buildEventChecklist } from '@/lib/event-progress'
import { saveEventPreparation } from '@/lib/supabase-progress'
import { WORKFLOW_LINKS } from '@/lib/workflow'
import type { Event,EventProgress,PreparationValues } from '@/lib/types'
export function EventChecklist({event,progress,canEdit,onChange}:{event:Event;progress:EventProgress;canEdit:boolean;onChange:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),steps=buildEventChecklist(event,progress,new Date())
 const update=async(key:keyof PreparationValues,value:boolean)=>{if(progress.state!=='loaded')return;setBusy(true);setError('');try{await saveEventPreparation(event.id,{...progress.preparation,[key]:value});onChange()}catch{setError('No se pudo guardar la confirmación. Intenta de nuevo.')}finally{setBusy(false)}}
 return <section className="card-uabc overflow-hidden"><div className="border-b bg-surface-2/60 p-5"><h2 className="font-display text-xl">Tu checklist del evento</h2><p className="mt-1 text-sm text-muted-foreground">{steps.filter(s=>s.state==='done').length} de {steps.length} pasos completados. Las confirmaciones manuales se distinguen de los datos verificados.</p></div><ol className="divide-y">{steps.map(step=><li key={step.id} className="p-5"><details open={step.state!=='done'}><summary className="flex cursor-pointer items-center gap-3 font-medium">{step.state==='done'?<CheckCircle2 className="h-5 w-5 shrink-0 text-primary"/>:step.state==='unverified'?<Clock className="h-5 w-5 shrink-0 text-muted-foreground"/>:<Circle className="h-5 w-5 shrink-0 text-muted-foreground"/>}{step.title}{step.state==='done'&&<span className="ml-auto text-xs font-normal text-muted-foreground">{step.source==='organizer'?'Confirmado por ti':'Verificado'}</span>}</summary><div className="ml-8 mt-3 space-y-3"><p className="text-sm leading-6 text-muted-foreground">{step.detail}</p>{step.href&&<Button asChild size="sm" variant="outline"><Link href={step.href}>{step.id==='report'?step.state==='done'?'Consultar reporte':'Completar reporte':step.id==='attendance'?'Ver QR y asistencia':'Corregir solicitud'}</Link></Button>}
 {step.id==='preparation'&&event.status==='aprobado'&&<><div className="flex flex-wrap gap-4 text-sm"><a href={WORKFLOW_LINKS.reservarEspacio} target="_blank" rel="noopener noreferrer" className="text-primary underline">Reservar espacio</a><a href={WORKFLOW_LINKS.plantillaDifusion} target="_blank" rel="noopener noreferrer" className="text-primary underline">Plantilla de difusión</a></div>{canEdit&&progress.state==='loaded'&&<div className="space-y-2">{([['reservationDone','Ya reservé el espacio'],['diffusionDone','Ya preparé la difusión']] as const).filter(([k])=>k!=='reservationDone'||event.modality!=='En línea').map(([key,label])=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={busy} checked={progress.preparation[key]} onChange={e=>void update(key,e.target.checked)}/>{label}</label>)}</div>}</>}
 {step.id==='attendance'&&canEdit&&event.status==='aprobado'&&progress.state==='loaded'&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={busy} checked={progress.preparation.qrShared} onChange={e=>void update('qrShared',e.target.checked)}/>Ya compartí el registro con los participantes</label>}</div></details></li>)}</ol>{progress.state==='unavailable'&&<div className="p-5"><p role="alert" className="text-sm">No pudimos consultar el seguimiento.</p><Button variant="outline" onClick={onChange}>Reintentar</Button></div>}{error&&<p className="p-5 text-sm text-destructive" role="alert">{error}</p>}</section>
}
